services:
  # create a SuperLink service
  superlink:
    image: flwr/superlink:${FLWR_VERSION:-1.17.0}
    command:
      - --insecure
      - --isolation
      - process
    ports:
      - 9093:9093

  # create a ServerApp service
  serverapp:
    build:
      context: ${PROJECT_DIR:-.}
      dockerfile: dockerfile-aggregator
    command:
      - --insecure
      - --serverappio-api-address
      - superlink:9091
    restart: on-failure:3
    depends_on:
      - superlink

  # create two SuperNode services with different node configs
  supernode-1:
    image: flwr/supernode:${FLWR_VERSION:-1.17.0}
    command:
      - --insecure
      - --superlink
      - superlink:9092
      - --clientappio-api-address
      - 0.0.0.0:9094
      - --isolation
      - process
      - --node-config
      - "partition-id=0 num-partitions=2"
    depends_on:
      - superlink

  supernode-2:
    image: flwr/supernode:${FLWR_VERSION:-1.17.0}
    command:
      - --insecure
      - --superlink
      - superlink:9092
      - --clientappio-api-address
      - 0.0.0.0:9095
      - --isolation
      - process
      - --node-config
      - "partition-id=1 num-partitions=2"
    depends_on:
      - superlink

  supernode-3:
    image: flwr/supernode:${FLWR_VERSION:-1.17.0}
    command:
      - --insecure
      - --superlink
      - superlink:9092
      - --clientappio-api-address
      - 0.0.0.0:9096
      - --isolation
      - process
      - --node-config
      - "partition-id=1 num-partitions=2"
    depends_on:
      - superlink

  supernode-4:
    image: flwr/supernode:${FLWR_VERSION:-1.17.0}
    command:
      - --insecure
      - --superlink
      - superlink:9092
      - --clientappio-api-address
      - 0.0.0.0:9097
      - --isolation
      - process
      - --node-config
      - "partition-id=1 num-partitions=2"
    depends_on:
      - superlink

#  supernode-5:
#    image: flwr/supernode:${FLWR_VERSION:-1.17.0}
#    command:
#      - --insecure
#      - --superlink
#      - superlink:9092
#      - --clientappio-api-address
#      - 0.0.0.0:9098
#      - --isolation
#      - process
#      - --node-config
#      - "partition-id=1 num-partitions=2"
#    depends_on:
#      - superlink

  # create two ClientApp services
  clientapp-1:
    build:
      context: ${PROJECT_DIR:-.}
      dockerfile: dockerfile-collaborator
    command:
      - --insecure
      - --clientappio-api-address
      - supernode-1:9094
    deploy:
      resources:
        limits:
          cpus: "2"
    stop_signal: SIGINT
    depends_on:
      - supernode-1

  clientapp-2:
    build:
      context: ${PROJECT_DIR:-.}
      dockerfile: dockerfile-collaborator
    command:
      - --insecure
      - --clientappio-api-address
      - supernode-2:9095
    deploy:
      resources:
        limits:
          cpus: "2"
    stop_signal: SIGINT
    depends_on:
      - supernode-2

  clientapp-3:
    build:
      context: ${PROJECT_DIR:-.}
      dockerfile: dockerfile-collaborator
    command:
      - --insecure
      - --clientappio-api-address
      - supernode-2:9096
    deploy:
      resources:
        limits:
          cpus: "2"
    stop_signal: SIGINT
    depends_on:
      - supernode-3

  clientapp-4:
    build:
      context: ${PROJECT_DIR:-.}
      dockerfile: dockerfile-collaborator
    command:
      - --insecure
      - --clientappio-api-address
      - supernode-2:9097
    deploy:
      resources:
        limits:
          cpus: "2"
    stop_signal: SIGINT
    depends_on:
      - supernode-4

#  clientapp-5:
#    build:
#      context: ${PROJECT_DIR:-.}
#      dockerfile: dockerfile-collaborator
#    command:
#      - --insecure
#      - --clientappio-api-address
#      - supernode-2:9098
#    deploy:
#      resources:
#        limits:
#          cpus: "2"
#    stop_signal: SIGINT
#    depends_on:
#      - supernode-5
