FROM flwr/serverapp:${FLWR_VERSION:-1.17.0}

# gcc is required for the fastai quickstart example
USER root
RUN apt-get update \
  && apt-get -y --no-install-recommends install \
  build-essential \
  && rm -rf /var/lib/apt/lists/*
USER app

WORKDIR /app
COPY --chown=app:app pyproject.toml .
RUN sed -i 's/.*flwr\[simulation\].*//' pyproject.toml \
  && python -m pip install -U --no-cache-dir .

COPY --chown=app:app Docker-Flower.txt .
RUN pip install -U -r Docker-Flower.txt \
  && pip freeze > Requirements-Docker-Flower.txt

ENTRYPOINT ["flwr-serverapp"]