services:
  aggregator:
    build: .
    context: ./app
    dockerfile: Dockerfile
    volumes:
      - .:/app
    entrypoint: jupyter lab --ip='0.0.0.0' --port=8888 --no-browser --allow-root
      --NotebookApp.token='' --NotebookApp.password=''
    image: image-python-3-11
    container_name: container-python-3-11/aggregator
