services:
  aggregator_openfl:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    entrypoint: jupyter lab --ip='0.0.0.0' --port=8888 --no-browser --allow-root
      --NotebookApp.token='' --NotebookApp.password=''
    image: openfl_projet
    container_name: openfl
