services:
  aggregator:
    image: image-python-3-11/aggregator
    container_name: container-aggregator

  collaborator_1:
    image: image-python-3-11/collaborator
    depends_on:
      - aggregator
    container_name: container-collaborator_1


    
    volumes:
      - ./certificates/col0_cert_folder.zip:/current_workspace/col0_cert_folder.zip
      - ./data/col0_data.zip:/current_workspace/data/col0_data.zip
    command:
      - /bin/sh
      - -c
      - |
        unzip -n /current_workspace/col0_cert_folder.zip
        unzip -o /current_workspace/data/col0_data.zip -d /current_workspace/data
        python3 start_collaborator.py
    environment:
      - COLLABORATOR_NAME=col0
      - PYTHONUNBUFFERED=1
